export const menuItems = [
  {
    id: "M001",
    name: "Phở Bò Tái",
    category: "Món chính",
    price: "₫65,000",
    status: "Còn hàng",
    image: "/pho-bo.png",
    description: "Phở bò truyền thống với thịt bò tái mềm và nước dùng đậm đà.",
    ingredients: [
      "Thịt bò",
      "Bánh phở",
      "Nước dùng xương",
      "Hành lá",
      "Ngò gai",
    ],
    allergens: ["Gluten"],
  },
  {
    id: "M002",
    name: "Bún Chả Hà Nội",
    category: "Món chính",
    price: "₫70,000",
    status: "Còn hàng",
    image: "/bun-cha.png",
    description:
      "Bún chả Hà Nội chuẩn vị với chả nướng thơm lừng và nước chấm chua ngọt.",
    ingredients: ["Thịt heo", "Bún", "Rau sống", "Nước chấm", "Đu đủ xanh"],
    allergens: ["Đậu phộng"],
  },
  {
    id: "M003",
    name: "Gỏi Cuốn",
    category: "Món khai vị",
    price: "₫45,000",
    status: "Còn hàng",
    image: "/goi-cuon.png",
    description:
      "Gỏi cuốn tươi ngon với tôm, thịt và rau sống, chấm nước mắm pha.",
    ingredients: ["Tôm", "Thịt heo", "Bún", "Rau sống", "Bánh tráng"],
    allergens: ["Hải sản"],
  },
  {
    id: "M004",
    name: "Cà Phê Sữa Đá",
    category: "Đồ uống",
    price: "₫30,000",
    status: "Còn hàng",
    image: "/placeholder-h0xr5.png",
    description: "Cà phê sữa đá Việt Nam đậm đà, thơm ngon.",
    ingredients: ["Cà phê", "Sữa đặc", "Đá"],
    allergens: ["Sữa"],
  },
  {
    id: "M005",
    name: "Chè Ba Màu",
    category: "Tráng miệng",
    price: "₫35,000",
    status: "Hết hàng",
    image: "/che-ba-mau.png",
    description: "Chè ba màu mát lạnh với đậu xanh, đậu đỏ và thạch.",
    ingredients: ["Đậu xanh", "Đậu đỏ", "Đậu trắng", "Nước cốt dừa", "Thạch"],
    allergens: ["Đậu"],
  },
  {
    id: "M006",
    name: "Bánh Mì Pate",
    category: "Món chính",
    price: "₫40,000",
    status: "Còn hàng",
    image: "/banh-mi-pate.png",
    description: "Bánh mì giòn rụm với pate, chả lụa và rau thơm.",
    ingredients: ["Bánh mì", "Pate", "Chả lụa", "Rau thơm", "Dưa chuột"],
    allergens: ["Gluten", "Trứng"],
  },
];

export const orders = [
  {
    id: "ORD001",
    table: "Bàn 1",
    customer: "Nguyễn Văn A",
    phone: "0901234567",
    overallStatus: "Đang nấu", // Trạng thái tổng thể của đơn hàng
    items: [
      { name: "Phở bò tái", quantity: 1, status: "Đang nấu" },
      { name: "Nước cam", quantity: 2, status: "Sẵn sàng" },
    ],
    total: "₫95,000",
    orderTime: "19:00",
    waitTime: "10 phút",
    server: "Thu Hà",
  },
  {
    id: "ORD002",
    table: "Bàn 3",
    customer: "Trần Thị B",
    phone: "0902345678",
    overallStatus: "Sẵn sàng",
    items: [
      { name: "Bún chả Hà Nội", quantity: 1, status: "Sẵn sàng" },
      { name: "Trà đá", quantity: 1, status: "Sẵn sàng" },
    ],
    total: "₫85,000",
    orderTime: "19:15",
    waitTime: "5 phút",
    server: "Minh Anh",
  },
  {
    id: "ORD003",
    table: "Bàn 5",
    customer: "Lê Văn C",
    phone: "0903456789",
    overallStatus: "Đã phục vụ",
    items: [
      { name: "Gỏi cuốn", quantity: 2, status: "Đã phục vụ" },
      { name: "Chè ba màu", quantity: 1, status: "Đã phục vụ" },
    ],
    total: "₫80,000",
    orderTime: "18:45",
    waitTime: "20 phút",
    server: "Thu Hà",
  },
  {
    id: "ORD004",
    table: "Bàn 7",
    customer: "Phạm Thị D",
    phone: "0904567890",
    overallStatus: "Chờ thanh toán",
    items: [
      { name: "Cơm tấm sườn", quantity: 1, status: "Đã phục vụ" },
      { name: "Canh chua", quantity: 1, status: "Đã phục vụ" },
    ],
    total: "₫120,000",
    orderTime: "18:30",
    waitTime: "30 phút",
    server: "Minh Anh",
  },
  {
    id: "ORD005",
    table: "Bàn 2",
    customer: "Hoàng Văn E",
    phone: "0905678901",
    overallStatus: "Đã hủy",
    items: [{ name: "Mì xào giòn", quantity: 1, status: "Đã hủy" }],
    total: "₫70,000",
    orderTime: "19:30",
    waitTime: "0 phút",
    server: "Thu Hà",
  },
  {
    id: "ORD006",
    table: "Bàn 4",
    customer: "Nguyễn Thị F",
    phone: "0906789012",
    overallStatus: "Đang nấu",
    items: [
      { name: "Bánh mì pate", quantity: 1, status: "Đang nấu" },
      { name: "Sữa đậu nành", quantity: 1, status: "Đang nấu" },
    ],
    total: "₫60,000",
    orderTime: "19:40",
    waitTime: "8 phút",
    server: "Minh Anh",
  },
  {
    id: "ORD007",
    table: "Bàn 6",
    customer: "Vũ Văn G",
    phone: "0907890123",
    overallStatus: "Sẵn sàng",
    items: [
      { name: "Lẩu thái", quantity: 1, status: "Sẵn sàng" },
      { name: "Nước ngọt", quantity: 3, status: "Sẵn sàng" },
    ],
    total: "₫350,000",
    orderTime: "19:50",
    waitTime: "3 phút",
    server: "Thu Hà",
  },
];
export const staff = [
  {
    id: "STF001",
    name: "Thu Hà",
    role: "Nhân viên phục vụ",
    phone: "0912345678",
    email: "thuha@ordergo.com",
    status: "Đang làm việc",
    assignedTables: ["T001", "T005"],
  },
  {
    id: "STF002",
    name: "Minh Anh",
    role: "Nhân viên phục vụ",
    phone: "0918765432",
    email: "minhanh@ordergo.com",
    status: "Đang làm việc",
    assignedTables: ["T003", "T007"],
  },
  {
    id: "STF003",
    name: "Quang Huy",
    role: "Đầu bếp",
    phone: "0987654321",
    email: "quanghuy@ordergo.com",
    status: "Đang làm việc",
    assignedTables: [],
  },
  {
    id: "STF004",
    name: "Thanh Mai",
    role: "Quản lý",
    phone: "0909112233",
    email: "thanhmai@ordergo.com",
    status: "Đang làm việc",
    assignedTables: [],
  },
  {
    id: "STF005",
    name: "Văn Nam",
    role: "Nhân viên phục vụ",
    phone: "0908765432",
    email: "vannam@ordergo.com",
    status: "Nghỉ phép",
    assignedTables: [],
  },
];
export const tables = [
  {
    id: "T001",
    name: "Bàn 1",
    capacity: 4,
    status: "Đang phục vụ",
    customers: 4,
    assignedStaffId: "STF001", // Thu Hà
    orderTime: "18:30",
    waitTime: "25 phút",
    total: "₫320,000",
    dishes: ["Phở bò", "Cơm gà", "Nước cam"],
  },
  {
    id: "T002",
    name: "Bàn 2",
    capacity: 2,
    status: "Trống",
    customers: 0,
    assignedStaffId: null,
    orderTime: null,
    waitTime: null,
    total: null,
    dishes: [],
  },
  {
    id: "T003",
    name: "Bàn 3",
    capacity: 6,
    status: "Chờ món",
    customers: 2,
    assignedStaffId: "STF002", // Minh Anh
    orderTime: "19:15",
    waitTime: "12 phút",
    total: "₫180,000",
    dishes: ["Bún bò Huế", "Chả cá"],
  },
  {
    id: "T004",
    name: "Bàn 4",
    capacity: 4,
    status: "Trống",
    customers: 0,
    assignedStaffId: null,
    orderTime: null,
    waitTime: null,
    total: null,
    dishes: [],
  },
  {
    id: "T005",
    name: "Bàn 5",
    capacity: 8,
    status: "Vừa gọi món",
    customers: 6,
    assignedStaffId: "STF001", // Thu Hà
    orderTime: "19:45",
    waitTime: "2 phút",
    total: "₫450,000",
    dishes: ["Lẩu thái", "Cơm chiên"],
  },
  {
    id: "T006",
    name: "Bàn 6",
    capacity: 2,
    status: "Trống",
    customers: 0,
    assignedStaffId: null,
    orderTime: null,
    waitTime: null,
    total: null,
    dishes: [],
  },
  {
    id: "T007",
    name: "Bàn 7",
    capacity: 4,
    status: "Chờ thanh toán",
    customers: 3,
    assignedStaffId: "STF002", // Minh Anh
    orderTime: "18:00",
    waitTime: "45 phút",
    total: "₫150,000",
    dishes: ["Cơm tấm", "Bánh mì", "Cà phê"],
  },
  {
    id: "T008",
    name: "Bàn 8",
    capacity: 6,
    status: "Trống",
    customers: 0,
    assignedStaffId: null,
    orderTime: null,
    waitTime: null,
    total: null,
    dishes: [],
  },
];
